apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-first-deployment
  namespace: work
  labels:
    app: &app nginx
    version: &version 1.27.5
spec:
  replicas: 3
  selector:
    matchLabels:
      app: *app
      version: *version
  template:
    metadata:
      name: my-first-pod
      namespace: work
      labels:
        app: nginx
        version: 1.27.5
    spec:
      containers:
        - name: nginx
          image: nginx:1.27.5
          ports:
            - containerPort: 80
          resources: { requests: { memory: "64Mi", cpu: "250m" }, limits: { memory: "64Mi", cpu: "500m" } }
